### ISSUE TITLE
CS:GO Update

### ISSUE THREAD

**Issue by kae1616** [abnerfs/round_start_sounds#1]
Sorry for bumping, kinda need this plugin for my new project.
Possible for you to update this plugin? 
Thanks!

**Comment by abnerfs** [comment]
Hi, plugin not working anymore?

**Comment by abnerfs** [comment]
i'm working on a update based on my Round End Sounds

**Comment by kae1616** [comment]
for csgo , sounds doesn’t get precache and downloaded. the codes are old , i did a pretty much rewrite but still didn’t work , guess i’ll wait for you to update it then.  thank you  !

**Comment by abnerfs** [comment]
https://github.com/abnerfs/round_start_sounds/releases

**Comment by kae1616** [comment]
congrats :)
gotta thank you for this one
