### ISSUE TITLE
SV_StartSound: *music/aot/aot.mp3 not precached (7562)

### ISSUE THREAD

**Issue by kae1616** [abnerfs/round_start_sounds#2]
Sounds still not getting precache , is it my problem or?

Console Logs:
SV_StartSound: *music/aot/aot.mp3 not precached (7562)

**Comment by abnerfs** [comment]
Check It the sounds are really downloaded in your sound folder (sound/music/aot/aot.mp3), If not we have a simple download issue in your server or cliente.

In server you need:
Sv_allowdownload 1
Sv_allowupload 1
If you have sv_downloadurl upload the sounds to the URL 


In client:
Cl_downloadfilter all

**Comment by kae1616** [comment]
anyway to force Cl_downloadfilter all ?
it fixes the problem, but by default, is  it set to 'all' ?

**Comment by kae1616** [comment]
nvm i did a implementation to kick when its set to any other than "all"

`#pragma semicolon 1
#include <sourcemod>

public OnClientPostAdminCheck(client)
{
    QueryClientConVar(client, "cl_downloadfilter", QueryConVar);
}

public QueryConVar(QueryCookie:cookie, client, ConVarQueryResult:result, const String:cvarName[], const String:cvarValue[])
{
    // all = download everything
    // nosounds = download all but sounds
    // mapsonly = only download maps, nothing else
    // none = don't download anything
    if (strcmp(cvarValue, "all", false) == 0)
    {
        return;
    }
    
    PrintToConsole(client, "You have your cl_downloadfilter set to [%s], please change it to [all]. Contact KaeMing if you need any support or visit our website!", cvarValue);
    PrintToConsole(client, "You have your cl_downloadfilter set to [%s], please change it to [all]. Contact KaeMing if you need any support or visit our website!", cvarValue);
    PrintToConsole(client, "You have your cl_downloadfilter set to [%s], please change it to [all]. Contact KaeMing if you need any support or visit our website!", cvarValue);
    KickClient(client, "Your setting for cl_downloadfilter is wrong, please set it to ALL! Contact KaeMing if you need any support or visit our website!");
    
    return;
}  `

**Comment by abnerfs** [comment]
Nice,  anyway "all" it's default value

**Comment by kae1616** [comment]
Finally got it fixed where the sounds are now downloaded but,
SV_StartSound: *music/aot/aot.mp3 not precached (7562)

still receiving the same error.

I also tried using your sound files:
SV_StartSound: *round_start/living_on_a_prayer.mp3 not precached (7563)

Also another thing which require a small fix, abners_rss.txt is in config folder and not configs, simple file moving will solve the problem.

Sounds are placed in round_start/living_on_a_prayer.mp3 


In case you need them, 

**cfg**

> // This file was auto-generated by SourceMod (v1.8.0.6041)
> // ConVars for plugin "abner_rss.smx"
> 
> 
> // Plugin version
> // -
> // Default: "2.0.0"
> abner_rss_version "2.0.0"
> 
> // Enable/Disable client preferences
> // -
> // Default: "1"
> rss_client_preferences "1"
> 
> // Default sound volume.
> // -
> // Default: "0.75"
> rss_default_volume "0.75"
> 
> // Path of sounds played when round starts
> // -
> // Default: "misc/tecnohard"
> rss_path "round_start"
> 
> // 1 - Random, 2 - Play in queue
> // -
> // Default: "1"
> rss_play_type "2"
> 
> // Print mp3 name in chat (Suggested by m22b)
> // -
> // Default: "1"
> rss_print_to_chat_mp3_name "1"
> 
> // Stop map musics
> // -
> // Default: "1"
> rss_stop_map_music "1"



**abner_rss.txt**

> "Abner RSS"
> {
>   "cant_stop.mp3"
>   {
>     "songname" "Tecnohard Start 1"
>   }
>    "eye_of_the_tiger.mp3"
>   {
>     "songname" "Tecnohard Start 2"
>   }
>    "follow_you_down.mp3"
>   {
>     "songname" "Tecnohard Start 3"
>   }
>    "geek_in_pink.mp3"
>   {
>     "songname" "Tecnohard Start 4"
>   }
>    "living_on_a_prayer.mp3"
>   {
>     "songname" "Tecnohard Start 5"
>   }
>   "papaoutai.mp3"
>   {
>     "songname" "Happy Birthday Song"
>   }
> }

**Comment by abnerfs** [comment]
try refresh the sounds using !rss_refresh command and see what happens, maybe sounds are being precached too late or something like that

**Comment by kae1616** [comment]
!rss_refresh did the trick

**Comment by abnerfs** [comment]
Of course i tested and i know servers that is already using This plugin and It Works

**Comment by abnerfs** [comment]
Maybe prechace sounds before add to download fix your issue
